// ============================================================
// 矿物别名/俗称映射表 v1.0
// 将常见俗称、变种名、行业术语映射到 IMA 标准矿物名称
// 格式: { alias → { target: "标准英文名", cn: "标准中文名", desc: "说明" } }
// ============================================================
var MINERAL_ALIASES = {
  // ==================== 石英 (Quartz) 家族 ====================
  "水晶": { target: "Quartz", cn: "石英", desc: "水晶是石英的透明晶体" },
  "紫水晶": { target: "Quartz", cn: "石英", desc: "紫水晶是石英的紫色变种" },
  "黄水晶": { target: "Quartz", cn: "石英", desc: "黄水晶是石英的黄色变种" },
  "烟水晶": { target: "Quartz", cn: "石英", desc: "烟水晶是石英的烟棕色变种" },
  "茶晶": { target: "Quartz", cn: "石英", desc: "茶晶是烟水晶的俗称，石英的变种" },
  "墨晶": { target: "Quartz", cn: "石英", desc: "墨晶是深色烟水晶（近黑色），石英的变种" },
  "粉晶": { target: "Quartz", cn: "石英", desc: "粉晶即玫瑰石英，石英的粉红色变种" },
  "芙蓉石": { target: "Quartz", cn: "石英", desc: "芙蓉石即粉晶/玫瑰石英" },
  "玫瑰石英": { target: "Quartz", cn: "石英", desc: "玫瑰石英是石英的粉红色块状变种" },
  "蔷薇石英": { target: "Quartz", cn: "石英", desc: "蔷薇石英即玫瑰石英" },
  "发晶": { target: "Quartz", cn: "石英", desc: "发晶是含有针状矿物包裹体的石英" },
  "钛晶": { target: "Quartz", cn: "石英", desc: "钛晶是含有金红石针状包裹体的石英" },
  "绿幽灵": { target: "Quartz", cn: "石英", desc: "绿幽灵是含有绿泥石包裹体的石英" },
  "红幽灵": { target: "Quartz", cn: "石英", desc: "红幽灵是含有红色氧化铁包裹体的石英" },
  "白幽灵": { target: "Quartz", cn: "石英", desc: "白幽灵是含有白色包裹体的石英" },
  "草莓晶": { target: "Quartz", cn: "石英", desc: "草莓晶是含有红色鳞片状包裹体的石英" },
  "兔毛晶": { target: "Quartz", cn: "石英", desc: "兔毛晶是含有细丝状包裹体的石英" },
  "乳石英": { target: "Quartz", cn: "石英", desc: "乳石英是白色半透明的石英变种" },
  "雪花晶": { target: "Quartz", cn: "石英", desc: "雪花晶是含有白色雪花状包裹体的石英" },
  "紫晶": { target: "Quartz", cn: "石英", desc: "紫晶即紫水晶，石英的紫色变种" },
  "黄晶": { target: "Quartz", cn: "石英", desc: "黄晶可指黄水晶（石英变种）" },
  "紫黄晶": { target: "Quartz", cn: "石英", desc: "紫黄晶是同时含紫色和黄色的石英变种" },
  "amethyst": { target: "Quartz", cn: "石英", desc: "Amethyst is a purple variety of Quartz" },
  "citrine": { target: "Quartz", cn: "石英", desc: "Citrine is a yellow variety of Quartz" },
  "rose quartz": { target: "Quartz", cn: "石英", desc: "Rose Quartz is a pink variety of Quartz" },
  "smoky quartz": { target: "Quartz", cn: "石英", desc: "Smoky Quartz is a brown variety of Quartz" },
  "rock crystal": { target: "Quartz", cn: "石英", desc: "Rock Crystal is the colorless transparent variety of Quartz" },
  "milky quartz": { target: "Quartz", cn: "石英", desc: "Milky Quartz is the white translucent variety of Quartz" },
  "prasiolite": { target: "Quartz", cn: "石英", desc: "Prasiolite is a green variety of Quartz" },
  "ametrine": { target: "Quartz", cn: "石英", desc: "Ametrine is a bicolor purple-yellow variety of Quartz" },
  "cairngorm": { target: "Quartz", cn: "石英", desc: "Cairngorm is a smoky quartz variety from Scotland" },

  // ==================== 隐晶质石英变种 ====================
  "玛瑙": { target: "Quartz", cn: "石英", desc: "玛瑙是隐晶质石英（玉髓）的带状变种" },
  "缠丝玛瑙": { target: "Quartz", cn: "石英", desc: "缠丝玛瑙是具有细密带状的玛瑙" },
  "苔藓玛瑙": { target: "Quartz", cn: "石英", desc: "苔藓玛瑙是含有苔藓状包裹体的玛瑙" },
  "水草玛瑙": { target: "Quartz", cn: "石英", desc: "水草玛瑙是含有水草状包裹体的玛瑙" },
  "南红": { target: "Quartz", cn: "石英", desc: "南红是红色玉髓/玛瑙的俗称，主产于云南、四川" },
  "南红玛瑙": { target: "Quartz", cn: "石英", desc: "南红玛瑙是红色玉髓/玛瑙" },
  "战国红": { target: "Quartz", cn: "石英", desc: "战国红是一种红黄相间的缟玛瑙" },
  "戈壁玛瑙": { target: "Quartz", cn: "石英", desc: "戈壁玛瑙产于戈壁滩的风蚀玛瑙" },
  "玉髓": { target: "Quartz", cn: "石英", desc: "玉髓是隐晶质石英的总称" },
  "绿玉髓": { target: "Quartz", cn: "石英", desc: "绿玉髓是含镍的绿色玉髓" },
  "澳洲玉": { target: "Quartz", cn: "石英", desc: "澳洲玉即绿玉髓" },
  "红玉髓": { target: "Quartz", cn: "石英", desc: "红玉髓即肉红色的玉髓" },
  "血玉髓": { target: "Quartz", cn: "石英", desc: "血玉髓即含有红色斑点的绿色玉髓" },
  "碧石": { target: "Quartz", cn: "石英", desc: "碧石（碧玉）是不透明的隐晶质石英" },
  "碧玉": { target: "Quartz", cn: "石英", desc: "碧玉在矿物学中指碧石（Jasper），是隐晶质石英" },
  "燧石": { target: "Quartz", cn: "石英", desc: "燧石是隐晶质石英，常含有机质" },
  "硅化木": { target: "Quartz", cn: "石英", desc: "硅化木是被石英质置换的木化石" },
  "虎眼石": { target: "Quartz", cn: "石英", desc: "虎眼石是纤维状石英交代石棉形成" },
  "鹰眼石": { target: "Quartz", cn: "石英", desc: "鹰眼石是蓝色的虎眼石（未完全氧化）" },
  "木变石": { target: "Quartz", cn: "石英", desc: "木变石是虎眼石的矿物学名称" },
  "agate": { target: "Quartz", cn: "石英", desc: "Agate is a banded variety of chalcedony (microcrystalline Quartz)" },
  "chalcedony": { target: "Quartz", cn: "石英", desc: "Chalcedony is a microcrystalline variety of Quartz" },
  "jasper": { target: "Quartz", cn: "石英", desc: "Jasper is an opaque variety of microcrystalline Quartz" },
  "carnelian": { target: "Quartz", cn: "石英", desc: "Carnelian is a red-orange variety of chalcedony" },
  "chrysoprase": { target: "Quartz", cn: "石英", desc: "Chrysoprase is a green variety of chalcedony" },
  "onyx": { target: "Quartz", cn: "石英", desc: "Onyx is a banded variety of chalcedony" },
  "sardonyx": { target: "Quartz", cn: "石英", desc: "Sardonyx is a banded variety combining sard and onyx" },
  "bloodstone": { target: "Quartz", cn: "石英", desc: "Bloodstone (heliotrope) is green chalcedony with red spots" },
  "flint": { target: "Quartz", cn: "石英", desc: "Flint is a sedimentary variety of microcrystalline Quartz" },
  "tiger eye": { target: "Quartz", cn: "石英", desc: "Tiger's Eye is a fibrous quartz replacing asbestos" },
  "hawk eye": { target: "Quartz", cn: "石英", desc: "Hawk's Eye is the blue unoxidized form of Tiger's Eye" },

  // ==================== 刚玉 (Corundum) 家族 ====================
  "红宝石": { target: "Corundum", cn: "刚玉", desc: "红宝石是含铬的红色刚玉" },
  "蓝宝石": { target: "Corundum", cn: "刚玉", desc: "蓝宝石是非红色的宝石级刚玉" },
  "黄色蓝宝石": { target: "Corundum", cn: "刚玉", desc: "黄色蓝宝石是黄色刚玉" },
  "粉色蓝宝石": { target: "Corundum", cn: "刚玉", desc: "粉色蓝宝石是粉色刚玉" },
  "帕帕拉恰": { target: "Corundum", cn: "刚玉", desc: "帕帕拉恰是橙粉色的蓝宝石" },
  "星光红宝石": { target: "Corundum", cn: "刚玉", desc: "星光红宝石是具星光效应的红色刚玉" },
  "星光蓝宝石": { target: "Corundum", cn: "刚玉", desc: "星光蓝宝石是具星光效应的蓝色刚玉" },
  "ruby": { target: "Corundum", cn: "刚玉", desc: "Ruby is a red variety of Corundum" },
  "sapphire": { target: "Corundum", cn: "刚玉", desc: "Sapphire is a non-red gem variety of Corundum" },
  "padparadscha": { target: "Corundum", cn: "刚玉", desc: "Padparadscha is a pink-orange variety of Corundum" },

  // ==================== 绿柱石 (Beryl) 家族 ====================
  "祖母绿": { target: "Beryl", cn: "绿柱石", desc: "祖母绿是含铬的绿色绿柱石" },
  "海蓝宝石": { target: "Beryl", cn: "绿柱石", desc: "海蓝宝石是蓝色至蓝绿色的绿柱石" },
  "海蓝宝": { target: "Beryl", cn: "绿柱石", desc: "海蓝宝即海蓝宝石，蓝色绿柱石" },
  "摩根石": { target: "Beryl", cn: "绿柱石", desc: "摩根石是粉红色的绿柱石" },
  "金绿柱石": { target: "Beryl", cn: "绿柱石", desc: "金绿柱石是黄色至金色的绿柱石" },
  "红绿柱石": { target: "Beryl", cn: "绿柱石", desc: "红绿柱石（红色绿柱石）极其稀有" },
  "emerald": { target: "Beryl", cn: "绿柱石", desc: "Emerald is a green variety of Beryl" },
  "aquamarine": { target: "Beryl", cn: "绿柱石", desc: "Aquamarine is a blue variety of Beryl" },
  "morganite": { target: "Beryl", cn: "绿柱石", desc: "Morganite is a pink variety of Beryl" },
  "heliodor": { target: "Beryl", cn: "绿柱石", desc: "Heliodor is a yellow variety of Beryl" },
  "goshenite": { target: "Beryl", cn: "绿柱石", desc: "Goshenite is the colorless variety of Beryl" },
  "bixbite": { target: "Beryl", cn: "绿柱石", desc: "Bixbite (Red Beryl) is the rare red variety of Beryl" },

  // ==================== 金绿宝石 (Chrysoberyl) 家族 ====================
  "猫眼": { target: "Chrysoberyl", cn: "金绿宝石", desc: "猫眼石通常指金绿宝石猫眼" },
  "猫眼石": { target: "Chrysoberyl", cn: "金绿宝石", desc: "猫眼石通常指金绿宝石猫眼" },
  "变石": { target: "Chrysoberyl", cn: "金绿宝石", desc: "变石（亚历山大石）是具变色效应的金绿宝石" },
  "亚历山大石": { target: "Chrysoberyl", cn: "金绿宝石", desc: "亚历山大石是变色金绿宝石" },
  "alexandrite": { target: "Chrysoberyl", cn: "金绿宝石", desc: "Alexandrite is a color-changing variety of Chrysoberyl" },
  "cat's eye": { target: "Chrysoberyl", cn: "金绿宝石", desc: "Cat's Eye usually refers to Chrysoberyl with chatoyancy" },

  // ==================== 石榴子石 (Garnet) 族 ====================
  "石榴石": { target: "Almandine", cn: "铁铝榴石", desc: "石榴石俗称通常指铁铝榴石" },
  "红石榴石": { target: "Pyrope", cn: "镁铝榴石", desc: "红石榴石通常指镁铝榴石" },
  "紫牙乌": { target: "Almandine", cn: "铁铝榴石", desc: "紫牙乌是铁铝榴石的旧称" },
  "翠榴石": { target: "Andradite", cn: "钙铁榴石", desc: "翠榴石是绿色钙铁榴石" },
  "沙弗莱": { target: "Grossular", cn: "钙铝榴石", desc: "沙弗莱石是绿色钙铝榴石" },
  "沙弗莱石": { target: "Grossular", cn: "钙铝榴石", desc: "沙弗莱石是含钒/铬的绿色钙铝榴石" },
  "芬达石": { target: "Spessartine", cn: "锰铝榴石", desc: "芬达石是橙色锰铝榴石" },
  "桂榴石": { target: "Grossular", cn: "钙铝榴石", desc: "桂榴石即橙色钙铝榴石" },
  "tsavorite": { target: "Grossular", cn: "钙铝榴石", desc: "Tsavorite is a green variety of Grossular" },
  "demantoid": { target: "Andradite", cn: "钙铁榴石", desc: "Demantoid is a green variety of Andradite" },
  "rhodolite": { target: "Pyrope", cn: "镁铝榴石", desc: "Rhodolite is a rose-red Pyrope-Almandine garnet" },
  "mandarin garnet": { target: "Spessartine", cn: "锰铝榴石", desc: "Mandarin Garnet is an orange variety of Spessartine" },
  "hessonite": { target: "Grossular", cn: "钙铝榴石", desc: "Hessonite is a cinnamon-colored variety of Grossular" },
  "malaia garnet": { target: "Pyrope", cn: "镁铝榴石", desc: "Malaia Garnet is a Pyrope-Spessartine blend" },

  // ==================== 电气石 (Tourmaline) 家族 ====================
  "碧玺": { target: "Elbaite", cn: "锂电气石", desc: "碧玺通常指锂电气石（宝石级电气石）" },
  "西瓜碧玺": { target: "Elbaite", cn: "锂电气石", desc: "西瓜碧玺是红绿双色的锂电气石" },
  "帕拉伊巴": { target: "Elbaite", cn: "锂电气石", desc: "帕拉伊巴碧玺是含铜的霓虹蓝绿色锂电气石" },
  "帕拉伊巴碧玺": { target: "Elbaite", cn: "锂电气石", desc: "帕拉伊巴碧玺是含铜的霓虹蓝绿色锂电气石" },
  "卢比来": { target: "Elbaite", cn: "锂电气石", desc: "卢比来是红色至粉红色的锂电气石" },
  "卢比莱": { target: "Elbaite", cn: "锂电气石", desc: "卢比莱（Rubellite）是红色锂电气石" },
  "黑碧玺": { target: "Schorl", cn: "黑电气石", desc: "黑碧玺即黑电气石（铁电气石）" },
  "tourmaline": { target: "Elbaite", cn: "锂电气石", desc: "Tourmaline gems are usually Elbaite species" },
  "rubellite": { target: "Elbaite", cn: "锂电气石", desc: "Rubellite is a red variety of Elbaite" },
  "paraiba": { target: "Elbaite", cn: "锂电气石", desc: "Paraíba tourmaline is a Cu-bearing neon blue-green Elbaite" },
  "indicolite": { target: "Elbaite", cn: "锂电气石", desc: "Indicolite is a blue variety of Elbaite" },
  "verdelite": { target: "Elbaite", cn: "锂电气石", desc: "Verdelite is a green variety of Elbaite" },
  "watermelon tourmaline": { target: "Elbaite", cn: "锂电气石", desc: "Watermelon Tourmaline is a bicolor variety of Elbaite" },

  // ==================== 翡翠 / 辉石族 ====================
  "翡翠": { target: "Jadeite", cn: "硬玉", desc: "翡翠的主要矿物成分是硬玉" },
  "缅甸玉": { target: "Jadeite", cn: "硬玉", desc: "缅甸玉即翡翠，主要产自缅甸" },
  "翠玉": { target: "Jadeite", cn: "硬玉", desc: "翠玉即翡翠" },
  "A货": { target: "Jadeite", cn: "硬玉", desc: "A货指天然未处理的翡翠" },
  "冰种翡翠": { target: "Jadeite", cn: "硬玉", desc: "冰种翡翠是高透明度的翡翠品种" },
  "玻璃种翡翠": { target: "Jadeite", cn: "硬玉", desc: "玻璃种翡翠是最高透明度的翡翠品种" },
  "帝王绿": { target: "Jadeite", cn: "硬玉", desc: "帝王绿指最高品质的鲜绿色翡翠" },
  "jade": { target: "Jadeite", cn: "硬玉", desc: "Jade commonly refers to Jadeite (or Nephrite)" },
  "jadeite jade": { target: "Jadeite", cn: "硬玉", desc: "Jadeite Jade is the more valued form of Jade" },
  "imperial jade": { target: "Jadeite", cn: "硬玉", desc: "Imperial Jade is the finest vivid green Jadeite" },

  // ==================== 软玉 / 角闪石族 ====================
  "和田玉": { target: "Tremolite", cn: "透闪石", desc: "和田玉的主要矿物成分是透闪石（软玉）" },
  "软玉": { target: "Tremolite", cn: "透闪石", desc: "软玉的主要矿物成分是透闪石" },
  "羊脂玉": { target: "Tremolite", cn: "透闪石", desc: "羊脂玉是和田玉中最优质的白玉品种" },
  "白玉": { target: "Tremolite", cn: "透闪石", desc: "白玉通常指白色和田玉（透闪石质）" },
  "青玉": { target: "Tremolite", cn: "透闪石", desc: "青玉是青色和田玉" },
  "青白玉": { target: "Tremolite", cn: "透闪石", desc: "青白玉介于白玉和青玉之间" },
  "墨玉": { target: "Tremolite", cn: "透闪石", desc: "墨玉是含石墨的黑色和田玉" },
  "黄玉": { target: "Tremolite", cn: "透闪石", desc: "黄玉在玉石界常指黄色和田玉" },
  "糖玉": { target: "Tremolite", cn: "透闪石", desc: "糖玉是含铁氧化物的褐色和田玉" },
  "碧玉（和田）": { target: "Tremolite", cn: "透闪石", desc: "和田碧玉是绿色透闪石质玉" },
  "nephrite": { target: "Tremolite", cn: "透闪石", desc: "Nephrite is a Tremolite-Actinolite series jade" },
  "nephrite jade": { target: "Tremolite", cn: "透闪石", desc: "Nephrite Jade is composed mainly of Tremolite" },
  "hetian jade": { target: "Tremolite", cn: "透闪石", desc: "Hetian (Hotan) Jade is premium Nephrite from Xinjiang" },
  "mutton fat jade": { target: "Tremolite", cn: "透闪石", desc: "Mutton Fat Jade is the finest white Nephrite" },

  // ==================== 长石 (Feldspar) 家族 ====================
  "月光石": { target: "Orthoclase", cn: "正长石", desc: "月光石通常是具有月光效应的正长石" },
  "冰长石": { target: "Orthoclase", cn: "正长石", desc: "冰长石是透明的正长石变种" },
  "天河石": { target: "Microcline", cn: "微斜长石", desc: "天河石是绿色微斜长石" },
  "亚马逊石": { target: "Microcline", cn: "微斜长石", desc: "亚马逊石即天河石" },
  "拉长石": { target: "Labradorite", cn: "拉长石", desc: "拉长石是具有晕彩效应的斜长石" },
  "光谱石": { target: "Labradorite", cn: "拉长石", desc: "光谱石是拉长石的俗称" },
  "日光石": { target: "Oligoclase", cn: "奥长石", desc: "日光石通常是含铜/赤铁矿片晶的长石" },
  "太阳石": { target: "Oligoclase", cn: "奥长石", desc: "太阳石即日光石" },
  "moonstone": { target: "Orthoclase", cn: "正长石", desc: "Moonstone is an Orthoclase with adularescence" },
  "amazonite": { target: "Microcline", cn: "微斜长石", desc: "Amazonite is a green variety of Microcline" },
  "sunstone": { target: "Oligoclase", cn: "奥长石", desc: "Sunstone is typically Oligoclase with aventurescence" },
  "labradorescence": { target: "Labradorite", cn: "拉长石", desc: "Labradorescence is the optical effect of Labradorite" },

  // ==================== 橄榄石 (Olivine) 家族 ====================
  "橄榄石": { target: "Forsterite", cn: "镁橄榄石", desc: "宝石级橄榄石主要是镁橄榄石" },
  "peridot": { target: "Forsterite", cn: "镁橄榄石", desc: "Peridot is the gem variety of Forsterite (Olivine)" },

  // ==================== 尖晶石 (Spinel) ====================
  "尖晶石": { target: "Spinel", cn: "尖晶石", desc: "尖晶石是独立矿物种" },
  "绝地武士尖晶石": { target: "Spinel", cn: "尖晶石", desc: "绝地武士尖晶石是高品质红色至粉红色尖晶石" },
  "钴尖晶石": { target: "Spinel", cn: "尖晶石", desc: "钴尖晶石是含钴的蓝色尖晶石" },

  // ==================== 锆石 (Zircon) ====================
  "锆石": { target: "Zircon", cn: "锆石", desc: "锆石是天然矿物，不是人造钻石" },
  "风信子石": { target: "Zircon", cn: "锆石", desc: "风信子石是橙红色锆石的旧称" },
  "hyacinth": { target: "Zircon", cn: "锆石", desc: "Hyacinth is the reddish-orange variety of Zircon" },

  // ==================== 钻石 (Diamond) ====================
  "钻石": { target: "Diamond", cn: "金刚石", desc: "钻石是宝石级金刚石" },
  "金刚钻": { target: "Diamond", cn: "金刚石", desc: "金刚钻即金刚石/钻石" },
  "鸽血红钻": { target: "Diamond", cn: "金刚石", desc: "鸽血红钻是红色钻石的商业名称" },
  "南非钻石": { target: "Diamond", cn: "金刚石", desc: "南非是重要的钻石产地" },

  // ==================== 欧泊 (Opal) ====================
  "欧泊": { target: "Opal", cn: "蛋白石", desc: "欧泊是蛋白石的宝石名称" },
  "澳宝": { target: "Opal", cn: "蛋白石", desc: "澳宝即澳大利亚蛋白石" },
  "黑欧泊": { target: "Opal", cn: "蛋白石", desc: "黑欧泊是深色背景的蛋白石" },
  "火欧泊": { target: "Opal", cn: "蛋白石", desc: "火欧泊是橙红色透明蛋白石" },
  "闪电岭欧泊": { target: "Opal", cn: "蛋白石", desc: "闪电岭是澳大利亚著名黑欧泊产地" },
  "black opal": { target: "Opal", cn: "蛋白石", desc: "Black Opal is the most valued variety of Opal" },
  "fire opal": { target: "Opal", cn: "蛋白石", desc: "Fire Opal is an orange-red transparent variety of Opal" },
  "boulder opal": { target: "Opal", cn: "蛋白石", desc: "Boulder Opal forms in ironstone cavities" },

  // ==================== 绿松石 (Turquoise) ====================
  "绿松石": { target: "Turquoise", cn: "绿松石", desc: "绿松石是独立矿物种" },
  "松石": { target: "Turquoise", cn: "绿松石", desc: "松石即绿松石" },
  "秦古料": { target: "Turquoise", cn: "绿松石", desc: "秦古料指产自湖北秦古的绿松石" },

  // ==================== 青金石 (Lazurite) ====================
  "青金石": { target: "Lazurite", cn: "青金石", desc: "青金石是独立矿物种" },
  "天青石": { target: "Celestine", cn: "天青石", desc: "天青石是独立矿物种（硫酸锶）" },
  "lapis lazuli": { target: "Lazurite", cn: "青金石", desc: "Lapis Lazuli is a rock mainly composed of Lazurite" },
  "lapis": { target: "Lazurite", cn: "青金石", desc: "Lapis is short for Lapis Lazuli" },

  // ==================== 孔雀石 (Malachite) ====================
  "孔雀石": { target: "Malachite", cn: "孔雀石", desc: "孔雀石是独立矿物种" },

  // ==================== 堇青石 (Cordierite/Iolite) ====================
  "堇青石": { target: "Cordierite", cn: "堇青石", desc: "堇青石是独立矿物种" },
  "水蓝宝石": { target: "Cordierite", cn: "堇青石", desc: "水蓝宝石是堇青石的商业名称" },
  "iolite": { target: "Cordierite", cn: "堇青石", desc: "Iolite is the gem name for Cordierite" },

  // ==================== 坦桑石 / 黝帘石 (Tanzanite/Zoisite) ====================
  "坦桑石": { target: "Zoisite", cn: "黝帘石", desc: "坦桑石是蓝紫色的宝石级黝帘石" },
  "坦桑尼亚石": { target: "Zoisite", cn: "黝帘石", desc: "坦桑尼亚石即坦桑石" },
  "tanzanite": { target: "Zoisite", cn: "黝帘石", desc: "Tanzanite is the blue-violet gem variety of Zoisite" },

  // ==================== 托帕石 / 黄玉 (Topaz) ====================
  "托帕石": { target: "Topaz", cn: "黄玉", desc: "托帕石即黄玉（矿物种）" },
  "黄宝石": { target: "Topaz", cn: "黄玉", desc: "黄宝石可能指黄色托帕石" },
  "帝王黄玉": { target: "Topaz", cn: "黄玉", desc: "帝王黄玉是橙黄色至粉橙色的黄玉" },
  "imperial topaz": { target: "Topaz", cn: "黄玉", desc: "Imperial Topaz is an orange to pink-orange Topaz" },
  "london blue topaz": { target: "Topaz", cn: "黄玉", desc: "London Blue Topaz is a deep blue irradiated Topaz" },
  "swiss blue topaz": { target: "Topaz", cn: "黄玉", desc: "Swiss Blue Topaz is a bright blue irradiated Topaz" },

  // ==================== 方柱石族 ====================
  "方柱石": { target: "Scapolite", cn: "方柱石", desc: "方柱石是独立矿物种" },

  // ==================== 磷灰石 (Apatite) ====================
  "磷灰石": { target: "Fluorapatite", cn: "氟磷灰石", desc: "常见磷灰石主要指氟磷灰石" },

  // ==================== 锂辉石 (Spodumene) 家族 ====================
  "锂辉石": { target: "Spodumene", cn: "锂辉石", desc: "锂辉石是独立矿物种" },
  "紫锂辉石": { target: "Spodumene", cn: "锂辉石", desc: "紫锂辉石（Kunzite）是粉紫色的锂辉石" },
  "翠绿锂辉石": { target: "Spodumene", cn: "锂辉石", desc: "翠绿锂辉石（Hiddenite）是绿色锂辉石" },
  "kunzite": { target: "Spodumene", cn: "锂辉石", desc: "Kunzite is a pink-violet variety of Spodumene" },
  "hiddenite": { target: "Spodumene", cn: "锂辉石", desc: "Hiddenite is a green variety of Spodumene" },

  // ==================== 方解石 (Calcite) ====================
  "方解石": { target: "Calcite", cn: "方解石", desc: "方解石是独立矿物种" },
  "冰洲石": { target: "Calcite", cn: "方解石", desc: "冰洲石是透明方解石（具双折射）" },
  "iceland spar": { target: "Calcite", cn: "方解石", desc: "Iceland Spar is the transparent variety of Calcite" },

  // ==================== 萤石 (Fluorite) ====================
  "萤石": { target: "Fluorite", cn: "萤石", desc: "萤石是独立矿物种" },
  "氟石": { target: "Fluorite", cn: "萤石", desc: "氟石即萤石" },

  // ==================== 云母族 ====================
  "云母": { target: "Muscovite", cn: "白云母", desc: "云母通常泛指白云母" },
  "金云母": { target: "Phlogopite", cn: "金云母", desc: "金云母是独立矿物种" },
  "黑云母": { target: "Annite", cn: "铁云母", desc: "黑云母现归类为铁云母" },

  // ==================== 工业/通用矿物俗称 ====================
  "石膏": { target: "Gypsum", cn: "石膏", desc: "石膏是独立矿物种" },
  "雪花石膏": { target: "Gypsum", cn: "石膏", desc: "雪花石膏是细粒白色石膏" },
  "沙漠玫瑰": { target: "Gypsum", cn: "石膏", desc: "沙漠玫瑰是玫瑰花状的石膏/重晶石集合体" },
  "alabaster": { target: "Gypsum", cn: "石膏", desc: "Alabaster is a fine-grained variety of Gypsum" },
  "desert rose": { target: "Gypsum", cn: "石膏", desc: "Desert Rose is a rosette formation of Gypsum" },
  "selenite": { target: "Gypsum", cn: "石膏", desc: "Selenite is the transparent crystal variety of Gypsum" },
  "石棉": { target: "Chrysotile", cn: "纤蛇纹石", desc: "最常见的石棉矿物是纤蛇纹石" },
  "asbestos": { target: "Chrysotile", cn: "纤蛇纹石", desc: "Most asbestos is Chrysotile (serpentine asbestos)" },
  "石灰石": { target: "Calcite", cn: "方解石", desc: "石灰石主要由方解石组成" },
  "大理石": { target: "Calcite", cn: "方解石", desc: "大理石主要由方解石变质形成" },
  "石英砂": { target: "Quartz", cn: "石英", desc: "石英砂是石英颗粒集合体" },
  "水晶球": { target: "Quartz", cn: "石英", desc: "水晶球由透明石英制成" },
  "硅石": { target: "Quartz", cn: "石英", desc: "硅石即石英/二氧化硅的工业名称" },
  "矾土": { target: "Gibbsite", cn: "三水铝石", desc: "矾土（铝土矿）的主要成分之一是三水铝石" },
  "明矾": { target: "Alunite", cn: "明矾石", desc: "明矾与明矾石相关" },
  "重晶石": { target: "Baryte", cn: "重晶石", desc: "重晶石是独立矿物种" },
  "石墨": { target: "Graphite", cn: "石墨", desc: "石墨是独立矿物种" },
  "铅笔芯": { target: "Graphite", cn: "石墨", desc: "铅笔芯的主要成分是石墨" },
  "黄铁矿": { target: "Pyrite", cn: "黄铁矿", desc: "黄铁矿是独立矿物种" },
  "愚人金": { target: "Pyrite", cn: "黄铁矿", desc: "愚人金是黄铁矿的俗称" },
  "fool's gold": { target: "Pyrite", cn: "黄铁矿", desc: "Fool's Gold is the common name for Pyrite" },
  "滑石": { target: "Talc", cn: "滑石", desc: "滑石是独立矿物种" },
  "皂石": { target: "Talc", cn: "滑石", desc: "皂石（肥皂石）主要由滑石组成" },
  "soapstone": { target: "Talc", cn: "滑石", desc: "Soapstone is a rock mainly composed of Talc" },
  "高岭土": { target: "Kaolinite", cn: "高岭石", desc: "高岭土主要由高岭石组成" },
  "瓷土": { target: "Kaolinite", cn: "高岭石", desc: "瓷土即高岭土" },

  // ==================== 金属矿物俗称 ====================
  "赤铁矿": { target: "Hematite", cn: "赤铁矿", desc: "赤铁矿是独立矿物种" },
  "铁矿石": { target: "Hematite", cn: "赤铁矿", desc: "铁矿石通常指赤铁矿或磁铁矿" },
  "磁铁矿": { target: "Magnetite", cn: "磁铁矿", desc: "磁铁矿是独立矿物种" },
  "吸铁石": { target: "Magnetite", cn: "磁铁矿", desc: "天然吸铁石通常是磁铁矿" },
  "黄铜矿": { target: "Chalcopyrite", cn: "黄铜矿", desc: "黄铜矿是独立矿物种" },
  "铜矿石": { target: "Chalcopyrite", cn: "黄铜矿", desc: "铜矿石通常指黄铜矿" },
  "方铅矿": { target: "Galena", cn: "方铅矿", desc: "方铅矿是独立矿物种" },
  "辰砂": { target: "Cinnabar", cn: "辰砂", desc: "辰砂是独立矿物种" },
  "朱砂": { target: "Cinnabar", cn: "辰砂", desc: "朱砂即辰砂的俗称" },
  "鸡血石": { target: "Cinnabar", cn: "辰砂", desc: "鸡血石中的红色部分主要是辰砂" },
  "雄黄": { target: "Realgar", cn: "雄黄", desc: "雄黄是独立矿物种" },
  "雌黄": { target: "Orpiment", cn: "雌黄", desc: "雌黄是独立矿物种" },
  "自然金": { target: "Gold", cn: "自然金", desc: "自然金是独立矿物种" },
  "沙金": { target: "Gold", cn: "自然金", desc: "沙金即砂矿中的自然金颗粒" },
  "狗头金": { target: "Gold", cn: "自然金", desc: "狗头金是大块天然金块" },
  "自然银": { target: "Silver", cn: "自然银", desc: "自然银是独立矿物种" },
  "自然铜": { target: "Copper", cn: "自然铜", desc: "自然铜是独立矿物种" },
  "自然铁": { target: "Iron", cn: "自然铁", desc: "自然铁极其稀有" },
  "铂金": { target: "Platinum", cn: "自然铂", desc: "铂金即自然铂" },
  "白金": { target: "Platinum", cn: "自然铂", desc: "白金即自然铂的俗称" },

  // ==================== 其他宝石矿物 ====================
  "蛇纹石": { target: "Antigorite", cn: "叶蛇纹石", desc: "蛇纹石通常指叶蛇纹石" },
  "岫玉": { target: "Antigorite", cn: "叶蛇纹石", desc: "岫玉主要由蛇纹石组成" },
  "岫岩玉": { target: "Antigorite", cn: "叶蛇纹石", desc: "岫岩玉即岫玉，蛇纹石质玉" },
  "独山玉": { target: "Zoisite", cn: "黝帘石", desc: "独山玉成分复杂，含有黝帘石等多种矿物" },
  "珊瑚": { target: "Calcite", cn: "方解石", desc: "宝石级珊瑚主要成分是方解石/文石" },
  "红珊瑚": { target: "Calcite", cn: "方解石", desc: "红珊瑚主要成分是方解石" },
  "珍珠": { target: "Aragonite", cn: "文石", desc: "珍珠主要由文石（霰石）组成" },
  "砗磲": { target: "Aragonite", cn: "文石", desc: "砗磲贝壳主要成分为文石" },
  "琥珀": { target: "ite", cn: "", desc: "琥珀是有机宝石（树脂化石），非矿物种" },
  "蜜蜡": { target: "ite", cn: "", desc: "蜜蜡是不透明的琥珀，非矿物种" },
  "舒俱来": { target: "Sugilite", cn: "杉石", desc: "舒俱来即杉石" },
  "舒俱来石": { target: "Sugilite", cn: "杉石", desc: "舒俱来石即杉石" },
  "查罗石": { target: "Charoite", cn: "紫龙晶", desc: "查罗石即紫龙晶" },
  "紫龙晶": { target: "Charoite", cn: "紫龙晶", desc: "紫龙晶即查罗石" },
  "拉利玛": { target: "Pectolite", cn: "针钠钙石", desc: "拉利玛（海纹石）是蓝色针钠钙石" },
  "海纹石": { target: "Pectolite", cn: "针钠钙石", desc: "海纹石即拉利玛，蓝色针钠钙石" },
  "larimar": { target: "Pectolite", cn: "针钠钙石", desc: "Larimar is a blue variety of Pectolite" },
  "孔雀石": { target: "Malachite", cn: "孔雀石", desc: "孔雀石是独立矿物种" },
  "蓝铜矿": { target: "Azurite", cn: "蓝铜矿", desc: "蓝铜矿是独立矿物种" },
  "石榴子石": { target: "Almandine", cn: "铁铝榴石", desc: "石榴子石最常见为铁铝榴石" },
  "青金": { target: "Lazurite", cn: "青金石", desc: "青金即青金石的简称" },
  "鸡血石矿": { target: "Cinnabar", cn: "辰砂", desc: "鸡血石的红色成分是辰砂" },
  "田黄": { target: "Pyrophyllite", cn: "叶蜡石", desc: "田黄石主要成分为叶蜡石" },
  "田黄石": { target: "Pyrophyllite", cn: "叶蜡石", desc: "田黄石主要成分为叶蜡石" },
  "寿山石": { target: "Pyrophyllite", cn: "叶蜡石", desc: "寿山石主要成分为叶蜡石" },
  "巴林石": { target: "Pyrophyllite", cn: "叶蜡石", desc: "巴林石主要成分为叶蜡石" },
  "昌化石": { target: "Pyrophyllite", cn: "叶蜡石", desc: "昌化石主要成分为叶蜡石" },
  "印章石": { target: "Pyrophyllite", cn: "叶蜡石", desc: "传统印章石多为叶蜡石质" },

  // ==================== 其他常见俗称 ====================
  "砂岩": { target: "Quartz", cn: "石英", desc: "砂岩主要由石英砂粒组成" },
  "水泥": { target: "Calcite", cn: "方解石", desc: "水泥生产以方解石（石灰石）为主要原料" },
  "石灰": { target: "Calcite", cn: "方解石", desc: "石灰由方解石（石灰石）煅烧而成" },
  "宝石": { target: "Corundum", cn: "刚玉", desc: "\"宝石\"泛称，最名贵的宝石包括钻石、红宝石、蓝宝石、祖母绿" },
  "雨花石": { target: "Quartz", cn: "石英", desc: "雨花石主要是石英质砾石" },
  "陨石": { target: "Kamacite", cn: "铁纹石", desc: "铁陨石主要成分为铁纹石" },
  "陨铁": { target: "Kamacite", cn: "铁纹石", desc: "陨铁主要成分为铁纹石和镍纹石" },
  "捷克陨石": { target: "ite", cn: "", desc: "捷克陨石（莫达维石）是天然玻璃，非矿物种" },
  "黑曜石": { target: "ite", cn: "", desc: "黑曜石是火山玻璃，非晶质，非严格矿物种" },
  "天珠": { target: "Quartz", cn: "石英", desc: "天然天珠多为条纹玛瑙（石英质）" },
  "鸡肝石": { target: "Quartz", cn: "石英", desc: "鸡肝石是含铁氧化物的碧石" },
  "文石": { target: "Aragonite", cn: "文石", desc: "文石即霰石" },
  "霰石": { target: "Aragonite", cn: "文石", desc: "霰石即文石" },
  "菱锰矿": { target: "Rhodochrosite", cn: "菱锰矿", desc: "菱锰矿是独立矿物种" },
  "红纹石": { target: "Rhodochrosite", cn: "菱锰矿", desc: "红纹石即菱锰矿的宝石名" },
  "印加玫瑰": { target: "Rhodochrosite", cn: "菱锰矿", desc: "印加玫瑰是菱锰矿的商业名称" },
  "蔷薇辉石": { target: "Rhodonite", cn: "蔷薇辉石", desc: "蔷薇辉石是独立矿物种" },
  "桃花石": { target: "Rhodonite", cn: "蔷薇辉石", desc: "桃花石可指蔷薇辉石" },
  "天蓝石": { target: "Lazulite", cn: "天蓝石", desc: "天蓝石是独立矿物种" },
  "蓝晶石": { target: "Kyanite", cn: "蓝晶石", desc: "蓝晶石是独立矿物种" },
  "红柱石": { target: "Andalusite", cn: "红柱石", desc: "红柱石是独立矿物种" },
  "空晶石": { target: "Andalusite", cn: "红柱石", desc: "空晶石（十字石状红柱石）是含碳质包裹体的红柱石" },
  "chiastolite": { target: "Andalusite", cn: "红柱石", desc: "Chiastolite is a cross-shaped variety of Andalusite" },
  "矽线石": { target: "Sillimanite", cn: "矽线石", desc: "矽线石是独立矿物种" },
  "硅线石": { target: "Sillimanite", cn: "矽线石", desc: "硅线石即矽线石" },
  "透辉石": { target: "Diopside", cn: "透辉石", desc: "透辉石是独立矿物种" },
  "铬透辉石": { target: "Diopside", cn: "透辉石", desc: "铬透辉石是含铬的绿色透辉石" },
  "chrome diopside": { target: "Diopside", cn: "透辉石", desc: "Chrome Diopside is a Cr-bearing green Diopside" },
  "硅灰石": { target: "Wollastonite", cn: "硅灰石", desc: "硅灰石是独立矿物种" },
  "透石膏": { target: "Gypsum", cn: "石膏", desc: "透石膏即透明板状石膏晶体" },
  "纤维石膏": { target: "Gypsum", cn: "石膏", desc: "纤维石膏是纤维状石膏变种" },
  "红宝": { target: "Corundum", cn: "刚玉", desc: "红宝即红宝石的简称" },
  "蓝宝": { target: "Corundum", cn: "刚玉", desc: "蓝宝即蓝宝石的简称" },
  "祖母绿宝石": { target: "Beryl", cn: "绿柱石", desc: "祖母绿宝石即祖母绿" },
  "坦桑": { target: "Zoisite", cn: "黝帘石", desc: "坦桑即坦桑石的简称" },
  "碧玺宝石": { target: "Elbaite", cn: "锂电气石", desc: "碧玺宝石即宝石级电气石" },
  "猫眼宝石": { target: "Chrysoberyl", cn: "金绿宝石", desc: "猫眼宝石通常指金绿宝石猫眼" },
  "变色宝石": { target: "Chrysoberyl", cn: "金绿宝石", desc: "变色宝石通常指亚历山大变石" },

  // ==================== 含锂矿物（工业热门）====================
  "锂矿": { target: "Spodumene", cn: "锂辉石", desc: "锂矿最主要的矿物来源是锂辉石" },
  "锂云母": { target: "Lepidolite", cn: "锂云母", desc: "锂云母是含锂的云母矿物" },

  // ==================== 稀土矿物 ====================
  "独居石": { target: "Monazite-(Ce)", cn: "独居石-(Ce)", desc: "独居石通常指铈独居石" },
  "氟碳铈矿": { target: "Bastnäsite-(Ce)", cn: "氟碳铈矿-(Ce)", desc: "氟碳铈矿是重要的稀土矿物" },

  // ==================== 收藏矿物热门搗称 ====================
  "黄铁": { target: "Pyrite", cn: "黄铁矿", desc: "黄铁即黄铁矿的简称" },
  "方铅": { target: "Galena", cn: "方铅矿", desc: "方铅即方铅矿的简称" },
  "萤石球": { target: "Fluorite", cn: "萤石", desc: "萤石球由萤石加工而成" },
  "紫萤石": { target: "Fluorite", cn: "萤石", desc: "紫萤石是紫色萤石" },
  "绿萤石": { target: "Fluorite", cn: "萤石", desc: "绿萤石是绿色萤石" },
  "蓝萤石": { target: "Fluorite", cn: "萤石", desc: "蓝萤石是蓝色萤石" },
  "闪锌矿": { target: "Sphalerite", cn: "闪锌矿", desc: "闪锌矿是独立矿物种" },
  "锑矿": { target: "Stibnite", cn: "辉锑矿", desc: "锑矿通常指辉锑矿" },
  "辉锑矿": { target: "Stibnite", cn: "辉锑矿", desc: "辉锑矿是独立矿物种" },
  "辉钼矿": { target: "Molybdenite", cn: "辉钼矿", desc: "辉钼矿是独立矿物种" },
  "钨矿": { target: "Wolframite", cn: "黑钨矿", desc: "钨矿通常指黑钨矿或白钨矿" },
  "黑钨矿": { target: "Wolframite", cn: "黑钨矿", desc: "黑钨矿是独立矿物种" },
  "白钨矿": { target: "Scheelite", cn: "白钨矿", desc: "白钨矿是独立矿物种" },
  "锡石": { target: "Cassiterite", cn: "锡石", desc: "锡石是独立矿物种" },
  "铬铁矿": { target: "Chromite", cn: "铬铁矿", desc: "铬铁矿是独立矿物种" },
  "钛铁矿": { target: "Ilmenite", cn: "钛铁矿", desc: "钛铁矿是独立矿物种" },
  "金红石": { target: "Rutile", cn: "金红石", desc: "金红石是独立矿物种" },
  "锐钛矿": { target: "Anatase", cn: "锐钛矿", desc: "锐钛矿是独立矿物种" },
  "板钛矿": { target: "Brookite", cn: "板钛矿", desc: "板钛矿是独立矿物种" },
  "菱铁矿": { target: "Siderite", cn: "菱铁矿", desc: "菱铁矿是独立矿物种" },
  "菱锌矿": { target: "Smithsonite", cn: "菱锌矿", desc: "菱锌矿是独立矿物种" },
  "异极矿": { target: "Hemimorphite", cn: "异极矿", desc: "异极矿是独立矿物种" },
  "硅锌矿": { target: "Willemite", cn: "硅锌矿", desc: "硅锌矿是独立矿物种" },
  "钒铅矿": { target: "Vanadinite", cn: "钒铅矿", desc: "钒铅矿是独立矿物种" },
  "磷氯铅矿": { target: "Pyromorphite", cn: "磷氯铅矿", desc: "磷氯铅矿是独立矿物种" },
  "蓝铅矿": { target: "Linarite", cn: "蓝铅矿", desc: "蓝铅矿是独立矿物种" },
  "针铁矿": { target: "Goethite", cn: "针铁矿", desc: "针铁矿是独立矿物种" },
  "褐铁矿": { target: "Goethite", cn: "针铁矿", desc: "褐铁矿主要成分为针铁矿" },
  "赤铜矿": { target: "Cuprite", cn: "赤铜矿", desc: "赤铜矿是独立矿物种" },
  "硅孔雀石": { target: "Chrysocolla", cn: "硅孔雀石", desc: "硅孔雀石是独立矿物种" }
};
